msrv = "1.90.0"
warn-on-all-wildcard-imports = true
cognitive-complexity-threshold = 30
type-complexity-threshold = 250
too-many-arguments-threshold = 7
too-many-lines-threshold = 100
avoid-breaking-exported-api = false
single-char-binding-names-threshold = 4
too-large-for-stack = 200
enum-variant-size-threshold = 200
unnecessary-box-size = 128
array-size-threshold = 512000
pass-by-value-size-limit = 256
min-ident-chars-threshold = 1

# 以下の設定は新しいバージョンのClippyでのみ利用可能
# Rust 1.80以降を使用する場合は、コメントを解除してください
# allow-unwrap-in-tests = true
# allow-expect-in-tests = true
# allow-panic-in-tests = true
