[env]
# having this set messes with tests as it'll be outside the sandbox
DOTNET_ROOT = { value = "", force = true }

[alias]
build = "build --target wasm32-wasip1"
format = "fmt --all --check"
lint = "clippy --all-targets --all-features -- -D warnings"
test = "test --test-threads=1"
release = "build --target wasm32-wasip1 --release"
