name: '[CI] Proto Tools'

on:
    push:
        branches:
        - prerelease
        paths:
        - '.github/workflows/ci.yml'
        - 'src/**'
        - 'tests/**'
        - 'Cargo.toml'
    pull_request:
        branches:
        - prerelease
        paths:
        - '.github/workflows/ci.yml'
        - 'src/**'
        - 'tests/**'
        - 'Cargo.toml'

jobs:
    run-format:
        runs-on: ${{ matrix.os }}

        strategy:
            matrix:
                os: [ubuntu-24.04, windows-2025, macos-15]
            fail-fast: false

        steps:
        - name: Checkout Repository
          uses: actions/checkout@v4.2.2

        - name: Setup Rust
          uses: moonrepo/setup-rust@v1.2.2
          with:
              cache: false
              components: rustfmt

        - name: Run Format
          run: cargo fmt --all --check

    run-lint:
        runs-on: ${{ matrix.os }}

        strategy:
            matrix:
                os: [ubuntu-24.04, windows-2025, macos-15]
            fail-fast: false

        steps:
        - name: Checkout Repository
          uses: actions/checkout@v4.2.2

        - name: Setup Rust
          uses: moonrepo/setup-rust@v1.2.2
          with:
              cache: false
              components: clippy

        - name: Run Lint
          run: cargo clippy --workspace --all-targets

    run-test:
        runs-on: ${{ matrix.os }}

        strategy:
            matrix:
                os: [ubuntu-24.04, windows-2025, macos-15]
            fail-fast: false

        steps:
        - name: Checkout Repository
          uses: actions/checkout@v4.2.2

        - name: Setup Rust
          uses: moonrepo/setup-rust@v1.2.2
          with:
              bins: cargo-nextest
              cache: false

        - name: Setup Toolchain
          uses: moonrepo/setup-toolchain@v0.5.0

        - name: Build Proto Plugin
          uses: moonrepo/build-proto-plugin@v0.4.2

        - name: Run Test
          run: cargo nextest run --no-default-features

    run-build:
        needs: [run-format, run-lint, run-test]

        runs-on: ${{ matrix.os }}

        strategy:
            matrix:
                os: [ubuntu-24.04, windows-2025, macos-15]
            fail-fast: false

        steps:
        - name: Checkout Repository
          uses: actions/checkout@v4.2.2

        - name: Setup Rust
          uses: moonrepo/setup-rust@v1.2.2
          with:
              cache: false
              targets: wasm32-wasip1

        - id: build
          name: Build Proto Plugin
          uses: moonrepo/build-wasm-plugin@v0.4.2

    run-approval:
        needs: run-build
        if: github.event_name == 'pull_request'

        runs-on: ubuntu-24.04

        steps:
        - name: Checkout Repository
          uses: actions/checkout@v4.2.2

        - name: Comment on PR when tests pass
          run: |
              comment_body="Tests passed! Please review."
              reviewers=$(echo '${{ toJson(github.event.pull_request.requested_reviewers.*.login) }}' | jq -r '.[]' 2>/dev/null || echo "")
              for reviewer in $reviewers; do
                comment_body+=" @$reviewer"
              done
              curl -X POST \
                -H "Authorization: token $GH_TOKEN" \
                -H "Accept: application/vnd.github.v3+json" \
                -d "{\"body\": \"$comment_body\"}" \
                "https://api.github.com/repos/$GH_REPO/issues/$NUMBER/comments"
          env:
              GH_TOKEN: ${{ secrets.PRE_GITHUB_TOKEN }}
              GH_REPO: ${{ github.repository }}
              NUMBER: ${{ github.event.pull_request.number }}
          if: success()
