name: "[Release] Proto Tools"

permissions:
    contents: write

on:
    push:
        tags:
        - 'v[0-9]+*'
    pull_request:

jobs:
    build:
        runs-on: ubuntu-24.04

        steps:
        - name: Checkout Repository
          uses: actions/checkout@v4.2.2

        - name: Setup Rust
          uses: moonrepo/setup-rust@v1.2.2
          with:
              cache: false

        - id: build
          name: Build Proto Plugin
          uses: moonrepo/build-wasm-plugin@v0.4.2

        - if: ${{ github.event_name == 'push' && github.ref_type == 'tag' }}
          name: Release
          uses: ncipollo/release-action@v1.18.0
          with:
              artifacts: builds/*
              artifactErrorsFailBuild: true
              body: ${{ steps.build.outputs.changelog-entry }}
              makeLatest: true
              prerelease: ${{ contains(github.ref_name, '-alpha') || contains(github.ref_name, '-beta') || contains(github.ref_name, '-rc') }}
              skipIfReleaseExists: true
