name: '[Release] Proto Tools'

permissions:
    contents: write

on:
    push:
        tags:
        - 'v[0-9]+*'

jobs:
    build:
        runs-on: ubuntu-24.04

        steps:
        - name: Checkout Repository
          uses: actions/checkout@v4.2.2

        - name: Setup Rust
          uses: moonrepo/setup-rust@v1.2.2
          with:
              cache: false
              targets: wasm32-wasip1

        - if: ${{ github.event_name == 'push' && github.ref_type == 'tag' }}
          id: build
          name: Build Proto Plugin
          uses: moonrepo/build-wasm-plugin@v0.4.2

    release:
        needs: build

        runs-on: ubuntu-24.04

        steps:
        - if: ${{ github.event_name == 'push' && github.ref_type == 'tag' }}
          name: Release
          uses: ncipollo/release-action@v1.18.0
          with:
              artifacts: ${{ steps.build.outputs.artifacts }}
              artifactErrorsFailBuild: true
              body: ${{ steps.build.outputs.changelog_entry }}
              makeLatest: true
              prerelease: ${{ contains(github.ref_name, '-alpha') || contains(github.ref_name, '-beta') || contains(github.ref_name, '-rc') }}
              skipIfReleaseExists: true

    update-changelog:
        needs: release

        runs-on: ubuntu-24.04

        steps:
        - if: ${{ github.event_name == 'push' && github.ref_type == 'tag' }}
          name: Update CHANGELOG
          run: |
              VERSION=${GITHUB_REF_NAME#v}

              if [ ! -f "CHANGELOG.md" ]; then
                  echo "CHANGELOG.md not found. Creating it..."
                  cat > CHANGELOG.md << EOF
              # Changelog

              ## $VERSION

              Release notes: https://github.com/${{ github.repository }}/releases/tag/${GITHUB_REF_NAME}
              EOF
              else
                  if grep -q "Unreleased" CHANGELOG.md; then
                      sed -i "s/Unreleased/$VERSION/" CHANGELOG.md
                  else
                      sed -i "/# Changelog/a\\\n## $VERSION\n\nRelease notes: https://github.com/${{ github.repository }}/releases/tag/${GITHUB_REF_NAME}\n" CHANGELOG.md
                  fi
              fi

              git config user.name "github-actions[bot]"
              git config user.email "github-actions[bot]@users.noreply.github.com"

              if git diff --quiet CHANGELOG.md; then
                  echo "No changes to CHANGELOG.md"
              else
                  git add CHANGELOG.md
                  git commit -m "docs: update CHANGELOG for $VERSION [skip ci]"
                  git push origin HEAD:${{ github.event.repository.default_branch }}
                  echo "CHANGELOG.md updated and pushed"
              fi
